openapi: 3.2.0
info:
  version: Latest
  title: Cumulocity Attachments API
  x-logo:
    url: https://www.cumulocity.com/docs/images/logo-platform.svg
    backgroundColor: '#F8F8F8'
    altText: Cumulocity
    href: https://www.cumulocity.com/api
  description: '# REST implementation


    This section describes the aspects common to all REST-based interfaces of Cumulocity. The interfaces are based on the Hypertext Transfer Protocol 1.1 using HTTPS. ## HTTP usage


    ### Application management


    Cumulocity uses a so-called "application key" to distinguish requests coming from devices and traffic from applications. If you write an application, pass the following header as part of all requests:


    ```markup

    X-Cumulocity-Application-Key:

    ```


    For example, if you registered your application in the Cumulocity Administration application with the key "myapp", your requests should contain the header:


    ```markup

    X-Cumulocity-Application-Key: myapp

    ```


    This makes your application subscribable and billable. If you implement a device, do not pass the key. > **ⓘ Info:** Make sure that you pass the key in **all** requests coming from an application. If you leave out the key,

    > the request will be considered as a device request, and the corresponding device will be marked as "available". ### Limited HTTP clients


    If you use an HTTP client that can only perform GET and POST methods in HTTP, you can emulate the other methods through an additional "X-HTTP-METHOD" header. Simply issue a POST request and add the header, specifying the actual REST method to be executed. For example, to emulate the "PUT" (modify) method, you can use:


    ```http

    POST ... X-HTTP-METHOD: PUT

    ```


    ### Processing mode


    Every update request (PUT, POST, DELETE) executes with a so-called *processing mode*. The processing modes are as follows:


    |Processing mode|Description|

    |---|---|

    |PERSISTENT (default)|Stores data in the Cumulocity database and sends data to the Streaming Analytics engine. Afterwards, Cumulocity returns the result of the request. This is the default mode.|

    |TRANSIENT|Sends data to the Streaming Analytics engine and immediately returns the results asynchronously but does not store data in Cumulocity’s database. This mode saves storage and processing costs and is useful for example when tracking devices in real time without requiring data to be stored.|

    |QUIESCENT|Behaves similar to the persistent mode with the exception that no real-time notifications will be sent.|

    |CEP|Behaves like the transient mode with the exception that no real-time notifications are sent.|


    To explicitly control the processing mode of an update request, you can use the "X-Cumulocity-Processing-Mode" header with a value of either "PERSISTENT", "TRANSIENT", "QUIESCENT" or "CEP":


    ```markup

    X-Cumulocity-Processing-Mode: PERSISTENT

    ```


    > **ⓘ Info:** Events are always delivered to CEP/Apama for all processing modes. This is independent from real-time notifications. ### Authorization


    All requests issued to Cumulocity are subject to authorization. To determine the required permissions, see the "Required role" entries for the individual requests. To learn more about the different permissions and the concept of ownership in Cumulocity, see Getting started > Technical concepts > Security aspects > Access control > Managing roles and assigning permissions in the Cumulocity user documentation. > **⚠️ Important:** In the Cumulocity API, each granular permission is identified by a unique “permission” string, which is prefixed with ROLE_ (for example, ROLE_ALARM_READ, ROLE_INVENTORY_ADMIN). Therefore, permissions are frequently referred to as “roles” throughout the API as well as in the configuration files. For example, the microservice manifest includes a requiredRoles field, which actually expects a permission string. See also the Glossary of the Cumulocity user documentation for the usage of the terms “permission” and “role” in the Cumulocity context. ### Media types


    Each type of data is associated with an own media type. The general format of media types is:


    ```markup

    application/vnd.com.nsn.cumulocity.+json;ver=;charset=UTF-8

    ```


    Each media type contains a parameter `ver` indicating the version of the type.'
servers:
- description: Cumulocity tenant
  url: https://<TENANT_DOMAIN>
security:
- Basic: []
- OAI-Secure: []
- SSO: []
- JWT-IAM: []
tags:
- name: Attachments
  description: It is possible to store, retrieve and delete binaries for events. Each event can have only one binary attached.
paths:
  /event/events/{id}/binaries:
    parameters:
    - $ref: '#/components/parameters/eventId'
    post:
      operationId: postEventBinaryResource
      x-codegen-resource-name: uploadEventAttachment
      tags:
      - Attachments
      security:
      - Basic: []
      - OAI-Secure: []
      - SSO: []
      summary: Attach a file to a specific event
      description: 'Upload a file (binary) as an attachment of a specific event by a given ID.

        The size of the attachment is configurable, and the default size is 50 MiB. The default chunk size is 5MiB.


        > **ⓘ Info:** If there is a binary already attached to the event, the POST request results in a 409 error.


        When the file has been uploaded, the corresponding event contains the fragment `c8y_IsBinary` similar to:


        ```json

        "c8y_IsBinary": {

        "name": "hello.txt",

        "length": 365,

        "type": "text/plain"

        }

        ```


        There are two request body schemas you can use for your POST requests.

        `text/plain` is preselected (see below).

        If you set it to `multipart/form-data` each value is sent as a block of data (body part), with a user agent-defined delimiter (`boundary`) separating each part.

        The keys are given in the `Content-Disposition` header of each part.


        ```http

        POST /event/events/{id}/binaries

        Host: https://

        Authorization:

        Accept: application/json

        Content-Type: multipart/form-data;boundary="boundary"


        --boundary

        Content-Disposition: form-data; name="object"


        { "name": "hello.txt", "type": "text/plain" }

        --boundary

        Content-Disposition: form-data; name="file"; filename="hello.txt"

        Content-Type: text/plain


        --boundary--

        ```


        Required roles


        ROLE_EVENT_ADMIN OR owner of the source OR EVENT_ADMIN permission on the source'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              description: The Content-Type must correspond to the file type.
              type: string
              format: binary
          multipart/form-data:
            schema:
              type: object
              required:
              - object
              - file
              properties:
                object:
                  $ref: '#/components/schemas/binaryInfo'
                file:
                  description: Path of the file to be uploaded.
                  type: string
                  format: binary
                  example: hello.txt
      x-code-samples:
      - lang: cURL
        source: 'curl --location --request POST "https://<TENANT_DOMAIN>/event/events/{id}/binaries" \

          --header "Authorization: Basic <AUTHORIZATION>" \

          --header "Accept: application/json" \

          --header "Content-Type: text/plain" \

          --data-binary "@/attachment/file.txt"

          '
      - lang: C#
        source: 'var client = new RestClient("https://<TENANT_DOMAIN>/event/events/{id}/binaries");

          client.Timeout = -1;


          var request = new RestRequest(Method.POST);

          request.AddHeader("Authorization", "Basic <AUTHORIZATION>");

          request.AddHeader("Accept", "application/json");

          request.AddParameter("text/plain", "<file contents here>", ParameterType.RequestBody);


          IRestResponse response = client.Execute(request);

          Console.WriteLine(response.Content);

          '
      - lang: Java
        source: "Unirest.setTimeouts(0, 0);\nHttpResponse<String> response = Unirest.post(\"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .header(\"Authorization\", \"Basic <AUTHORIZATION>\")\n    .header(\"Accept\", \"application/json\")\n    .body(\"<file contents here>\")\n    .asString();\nSystem.out.println(response);\n"
      - lang: Node.js
        source: "var unirest = require(\"unirest\");\nvar req = unirest(\"POST\", \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .headers({\n        \"Authorization\": \"Basic <AUTHORIZATION>\",\n        \"Accept\": \"application/json\",\n        \"Content-Type\": \"text/plain\"\n    })\n    .send(\"<file contents here>\")\n    .end(function (res) {\n        if (res.error) throw new Error(res.error);\n        console.log(res.raw_body);\n    });\n"
      - lang: Python
        source: "import requests\n\nurl = \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\"\nheaders = {\n  \"Authorization\": \"Basic <AUTHORIZATION>\",\n  \"Accept\": \"application/json\",\n  \"Content-Type\": \"text/plain\"\n}\nresponse = requests.request(\"POST\", url, headers=headers, data = \"<file contents here>\")\nprint(response.text.encode(\"utf8\"))\n"
      responses:
        '201':
          description: A file was uploaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventBinary'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/operationNotAuthorized'
        '404':
          $ref: '#/components/responses/eventNotFound'
        '409':
          $ref: '#/components/responses/attachmentDuplicated'
    get:
      operationId: getEventBinaryResource
      x-codegen-resource-name: getEventAttachment
      tags:
      - Attachments
      security:
      - Basic: []
      - OAI-Secure: []
      - SSO: []
      summary: Retrieve the attached file of a specific event
      description: 'Retrieve the attached file (binary) of a specific event by a given ID.


        Required roles


        ROLE_EVENT_READ OR owner of the source OR EVENT_READ permission on the source'
      x-code-samples:
      - lang: cURL
        source: 'curl --location --request GET "https://<TENANT_DOMAIN>/event/events/{id}/binaries" \

          --header "Authorization: Basic <AUTHORIZATION>"

          '
      - lang: C#
        source: 'var client = new RestClient("https://<TENANT_DOMAIN>/event/events/{id}/binaries");

          client.Timeout = -1;


          var request = new RestRequest(Method.GET);

          request.AddHeader("Authorization", "Basic <AUTHORIZATION>");


          IRestResponse response = client.Execute(request);

          Console.WriteLine(response.Content);

          '
      - lang: Java
        source: "Unirest.setTimeouts(0, 0);\nHttpResponse<String> response = Unirest.get(\"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .header(\"Authorization\", \"Basic <AUTHORIZATION>\").asString();\nSystem.out.println(response);\n"
      - lang: Node.js
        source: "var unirest = require(\"unirest\");\nvar req = unirest(\"GET\", \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .headers({\n        \"Authorization\": \"Basic <AUTHORIZATION>\"\n    })\n    .end(function (res) {\n        if (res.error) throw new Error(res.error);\n        console.log(res.raw_body);\n    });\n"
      - lang: Python
        source: "import requests\n\nurl = \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\"\nheaders = {\n  \"Authorization\": \"Basic <AUTHORIZATION>\"\n}\nresponse = requests.request(\"GET\", url, headers=headers)\nprint(response.text.encode(\"utf8\"))\n"
      responses:
        '200':
          description: The request has succeeded and the file is sent in the response.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/operationNotAuthorized'
        '404':
          $ref: '#/components/responses/attachmentNotFound'
    put:
      operationId: putEventBinaryResource
      x-codegen-resource-name: replaceEventAttachment
      tags:
      - Attachments
      security:
      - Basic: []
      - OAI-Secure: []
      - SSO: []
      summary: Replace the attached file of a specific event
      description: 'Upload and replace the attached file (binary) of a specific event by a given ID.


        The size of the attachment is configurable, and the default size is 50 MiB. The default chunk size is 5MiB.


        You can use two types of Content-Type headers for your PUT requests:

        * text/plain is the default.

        * application/octet-stream indicates that the request body contains arbitrary binary data. In this case, parameters should be specified in the Content-Disposition header.


        ```http

        PUT /event/events/{id}/binaries

        Host: https://

        Authorization:

        Accept: application/json

        Content-Type: application/octet-stream

        Content-Disposition: attachment; filename="filename.txt"

        ```


        Required roles


        ROLE_EVENT_ADMIN OR owner of the source OR EVENT_ADMIN permission on the source'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              format: binary
          application/octet-stream:
            schema:
              type: string
              format: binary
              description: The request body contains binary data. The encoded string represents a file (e.g., an image, document, etc.), and the server will decode it upon receipt.
      x-code-samples:
      - lang: cURL
        source: 'curl --location --request PUT "https://<TENANT_DOMAIN>/event/events/{id}/binaries" \

          --header "Authorization: Basic <AUTHORIZATION>" \

          --header "Accept: application/json" \

          --header "Content-Type: text/plain" \

          --data-binary "@/attachment/file.txt"

          '
      - lang: C#
        source: 'var client = new RestClient("https://<TENANT_DOMAIN>/event/events/{id}/binaries");

          client.Timeout = -1;


          var request = new RestRequest(Method.PUT);

          request.AddHeader("Authorization", "Basic <AUTHORIZATION>");

          request.AddHeader("Accept", "application/json");

          request.AddParameter("text/plain", "<file contents here>", ParameterType.RequestBody);


          IRestResponse response = client.Execute(request);

          Console.WriteLine(response.Content);

          '
      - lang: Java
        source: "Unirest.setTimeouts(0, 0);\nHttpResponse<String> response = Unirest.put(\"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .header(\"Authorization\", \"Basic <AUTHORIZATION>\")\n    .header(\"Accept\", \"application/json\")\n    .body(\"<file contents here>\")\n    .asString();\nSystem.out.println(response);\n"
      - lang: Node.js
        source: "var unirest = require(\"unirest\");\nvar req = unirest(\"PUT\", \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .headers({\n        \"Authorization\": \"Basic <AUTHORIZATION>\",\n        \"Accept\": \"application/json\",\n        \"Content-Type\": \"text/plain\"\n    })\n    .send(\"<file contents here>\")\n    .end(function (res) {\n        if (res.error) throw new Error(res.error);\n        console.log(res.raw_body);\n    });\n"
      - lang: Python
        source: "import requests\n\nurl = \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\"\nheaders = {\n  \"Authorization\": \"Basic <AUTHORIZATION>\",\n  \"Accept\": \"application/json\",\n  \"Content-Type\": \"text/plain\"\n}\nresponse = requests.request(\"PUT\", url, headers=headers, data = \"<file contents here>\")\nprint(response.text.encode(\"utf8\"))\n"
      responses:
        '201':
          description: A file was uploaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/eventBinary'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/operationNotAuthorized'
        '404':
          $ref: '#/components/responses/eventNotFound'
    delete:
      operationId: deleteEventBinaryResource
      x-codegen-resource-name: deleteEventAttachment
      tags:
      - Attachments
      security:
      - Basic: []
      - OAI-Secure: []
      - SSO: []
      summary: Remove the attached file from a specific event
      description: 'Remove the attached file (binary) from a specific event by a given ID.


        Required roles


        ROLE_EVENT_ADMIN OR owner of the source OR EVENT_ADMIN permission on the source'
      x-code-samples:
      - lang: cURL
        source: 'curl --location --request DELETE "https://<TENANT_DOMAIN>/event/events/{id}/binaries" \

          --header "Authorization: Basic <AUTHORIZATION>"

          '
      - lang: C#
        source: 'var client = new RestClient("https://<TENANT_DOMAIN>/event/events/{id}/binaries");

          client.Timeout = -1;


          var request = new RestRequest(Method.DELETE);

          request.AddHeader("Authorization", "Basic <AUTHORIZATION>");


          IRestResponse response = client.Execute(request);

          Console.WriteLine(response.Content);

          '
      - lang: Java
        source: "Unirest.setTimeouts(0, 0);\nHttpResponse<String> response = Unirest.delete(\"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .header(\"Authorization\", \"Basic <AUTHORIZATION>\").asString();\nSystem.out.println(response);\n"
      - lang: Node.js
        source: "var unirest = require(\"unirest\");\nvar req = unirest(\"DELETE\", \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\")\n    .headers({\n        \"Authorization\": \"Basic <AUTHORIZATION>\"\n    })\n    .end(function (res) {\n        if (res.error) throw new Error(res.error);\n        console.log(res.raw_body);\n    });\n"
      - lang: Python
        source: "import requests\n\nurl = \"https://<TENANT_DOMAIN>/event/events/{id}/binaries\"\nheaders = {\n  \"Authorization\": \"Basic <AUTHORIZATION>\"\n}\nresponse = requests.request(\"DELETE\", url, headers=headers)\nprint(response.text.encode(\"utf8\"))\n"
      responses:
        '204':
          description: A file was removed.
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/operationNotAuthorized'
        '404':
          $ref: '#/components/responses/eventNotFound'
components:
  schemas:
    eventBinary:
      type: object
      properties:
        name:
          description: Name of the attachment. If it is not provided in the request, it will be set as the event ID.
          type: string
        self:
          $ref: '#/components/schemas/desc_self'
        source:
          description: Unique identifier of the event.
          type: string
          readOnly: true
        type:
          description: Media type of the attachment.
          type: string
      example:
        name: hello.txt
        self: https://<TENANT_DOMAIN>/event/events/102522209/binaries
        source: '102522209'
        type: text/plain
    desc_self:
      title: SelfURL
      description: A URL linking to this resource.
      type: string
      format: uri
      readOnly: true
    error:
      type: object
      properties:
        error:
          description: The type of error returned.
          type: string
        message:
          description: A human-readable message providing more details about the error.
          type: string
        info:
          description: A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that identifies the error code reported.
          type: string
    binaryInfo:
      description: Contains information about the file.
      type: object
      properties:
        name:
          description: Name of the binary object.
          type: string
          maxLength: 1000
          example: HelloWorld
        type:
          description: Media type of the file.
          type: string
          maxLength: 1000
          example: text/plain
  responses:
    operationNotAuthorized:
      description: Not authorized to perform this operation.
    eventNotFound:
      description: Event not found.
      content:
        application/vnd.com.nsn.cumulocity.error+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error: event/Not Found
            message: Finding event from database failed
            info: https://www.cumulocity.com/guides/reference-guide/#error_reporting
    unauthorizedError:
      description: Authentication information is missing or invalid.
      content:
        application/vnd.com.nsn.cumulocity.error+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error: security/Unauthorized
            message: 'Invalid credentials! : Bad credentials'
            info: https://www.cumulocity.com/guides/reference-guide/#error_reporting
    attachmentDuplicated:
      description: An attachment exists already.
      content:
        application/vnd.com.nsn.cumulocity.error+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error: Duplicate
            message: Attachment already exists
            info: https://www.cumulocity.com/guides/reference-guide/#error_reporting
    attachmentNotFound:
      description: Attachment not found.
      content:
        application/vnd.com.nsn.cumulocity.error+json:
          schema:
            $ref: '#/components/schemas/error'
          example:
            error: Not Found
            message: Attachment not found
            info: https://www.cumulocity.com/guides/reference-guide/#error_reporting
  parameters:
    eventId:
      name: id
      in: path
      description: Unique identifier of the event.
      required: true
      schema:
        type: string
        minLength: 1
        example: '20200301'
  securitySchemes:
    Basic:
      type: http
      scheme: basic
      description: 'The authorization header is formed as `Basic <Base64(<tenantID>/<c8yuser>:<password>)>`. For instance, if your tenantID, username and password are **t0071234**, **testuser** and **secret123** respectively, you can generate the Base64 string with the following command:


        ```shell

        $ echo -n t0071234/testuser:secret123 | base64

        ```


        and your authorization header would look like this:


        ```

        "Authorization": "Basic dDAwNzEyMzQvdGVzdHVzZXI6c2VjcmV0MTIz"

        ```

        '
    OAI-Secure:
      type: http
      scheme: bearer
      description: 'This is the recommended authorization method because it provides high security using authorization tokens to prove the identity of the user, and it is the default login mode on creating new tenants. This mode is an enhancement of the previous OAuth Internal authentication (available prior to 10.13.0).


        For more details about OAI-Secure authentication, see [Platform administration > Authentication > Basic settings > Login settings](https://www.cumulocity.com/docs/authentication/basic-settings/#login-settings) in the Cumulocity user documentation.

        '
    SSO:
      type: oauth2
      description: "The login with SSO requires a correct configuration on the [Cumulocity side](https://www.cumulocity.com/docs/authentication/sso/). With the configuration, an additional button is available on the Login page. After clicking the button, the user is redirected to authenticate with the configured authorization server. On successful login, the user is redirected to Cumulocity.\n\nAuthentication details are exchanged using cookies. There are two parts to it, the first is the authentication cookie that is handled automatically by the Cumulocity platform. The second is the XSRF-TOKEN cookie. When a client receives the cookie, it should take the value and put it in the X-XSRF-TOKEN request header in all subsequent requests.\n\nThe flow of authenticating with authentication code grant is as follows:\n\n![Authentication flow](images/oauth-simple-flow.png)\n\nThe first request executed by the browser is:\n\n```http\nGET /tenant/loginOptions\nHost: https://<TENANT_DOMAIN>\nAccept: application/vnd.com.nsn.cumulocity.loginoptioncollection+json\n```\n\nResponse sample:\n\n```json\n{\n    \"loginOptions\": [\n        {\n            \"buttonName\": \"Login with oauth\",\n            \"grantType\": \"<AUTHORIZATION_CODE>\",\n            \"initRequest\": \"https://<TENANT_DOMAIN>/tenant/oauth?response_type=code&tenant_id=<TENANT_ID>\",\n            \"self\": \"https://<TENANT_DOMAIN>/tenant/loginOptions/oauth2\",\n            \"type\": \"oauth2\"\n        },\n        ...\n    ],\n    \"self\": \"http://<TENANT_DOMAIN>/tenant/loginOptions/\"\n}\n```\n\nThe browser must invoke the request provided in the initRequest parameter.\n\nThe initRequest initiates the redirect, in which the user is prompted for credentials. After successful login, the user is redirected back to the browser, where it must capture the code request parameter. Then the request to exchange the code for the token is as follows:\n\n```http\nPOST /tenant/oauth?grant_type=authorization_code&code=<CODE>\nHost: https://<TENANT_DOMAIN>\n```\n\nA successful response will have no body but the following response headers:\n\n```\nSet-Cookie: authorization=<TOKEN>;\nSet-Cookie: XSRF-TOKEN=<XSRF-TOKEN>;\n```\n\nThe authorization cookie is valid for two weeks.\n"
      flows:
        clientCredentials:
          tokenUrl: /tenant/oauth?grant_type=authorization_code&code=<CODE>
          scopes: {}
    JWT-IAM:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'This kind of authentication substitutes the JWT authentication with OAuth2 access tokens from your Identity and Access Management (IAM).

        You can enable this in the [SSO configuration](https://www.cumulocity.com/docs/authentication/sso/).


        The HTTP header must include:


        ```

        "Authorization": "Bearer <Access token>"

        ```


        When a request with a bearer token in the header is received, Cumulocity checks if the access token is from your IAM (that is, if authentication is enabled in your SSO configuration), and verifies the authenticity of

        the token remotely against the IAM.

        '
x-tagGroups:
- name: Platform
  tags:
  - Platform API
- name: Alarms
  tags:
  - Alarm API
  - Alarm notification API
  - Alarms
- name: Applications
  tags:
  - Application API
  - Applications
  - Application versions
  - Application binaries
  - Bootstrap user
  - Current application
- name: Audits
  tags:
  - Audit API
  - Audits
- name: Device control
  tags:
  - Device control API
  - Device control notification API
  - Operations
  - Bulk operations
  - Device credentials
  - New device requests
  - Device control via SMS
- name: Events
  tags:
  - Event API
  - Event notification API
  - Events
  - Attachments
- name: Feature toggles
  tags:
  - Feature toggles API
- name: Identity
  tags:
  - Identity API
  - External IDs
- name: Inventory
  tags:
  - Inventory API
  - Inventory notification API
  - Managed objects
  - Binaries
  - Child operations
  - Query language
- name: Measurements
  tags:
  - Measurement API
  - Measurement notification API
  - Measurements
  - Measurements specifics
- name: Notifications 2.0
  tags:
  - About notifications 2.0
  - Notification 2.0 API
  - Subscriptions
  - Tokens
- name: Real-time notifications
  tags:
  - Real-time notification API
- name: Retentions
  tags:
  - Retention rules
- name: Tenants
  tags:
  - Tenant API
  - Tenants
  - Tenant applications
  - Trusted certificates
  - Device statistics
  - Usage statistics
  - Options
  - Login options
  - Login tokens
  - System options
- name: Users
  tags:
  - User API
  - Current User
  - Users
  - Groups
  - Roles
  - Inventory Roles
  - Device Permissions
- name: Certificate
  tags:
  - Certificate authority
  - Device enrollment
